//
//  PostDetailsViewControllerTests.swift
//  VIP-Demo
//
//  Created by admin on 4/1/19.
//  Copyright (c) 2019 admin. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import VIP_Demo
import XCTest

class PostDetailsViewControllerTests: XCTestCase
{
  // MARK: Subject under test
  
  var sut: PostDetailsViewController!
  var window: UIWindow!
  
  // MARK: Test lifecycle
  
  override func setUp()
  {
    super.setUp()
    window = UIWindow()
    setupPostDetailsViewController()
  }
  
  override func tearDown()
  {
    window = nil
    super.tearDown()
  }
  
  // MARK: Test setup
  
  func setupPostDetailsViewController()
  {
    sut = PostDetailsViewController()
  }
  
  func loadView()
  {
    window.addSubview(sut.view)
    RunLoop.current.run(until: Date())
  }
  
  // MARK: Test doubles
  
  class PostDetailsBusinessLogicSpy: PostDetailsBusinessLogic
  {
    var fetchPostCalled = false
    
    func fetchPosts(request: PostDetails.Post.Request) {
    
      fetchPostCalled = true
    }
  }
  
  // MARK: Tests
  
  func testfetchPosts()
  {
    // Given
    let spy = PostDetailsBusinessLogicSpy()
    sut.interactor = spy
    sut.fetchPosts()
    // When
    loadView()
    
    // Then
    XCTAssertTrue(spy.fetchPostCalled, "viewDidLoad() should ask the interactor to do fetch posts")
  }
  
  func testdisplayPosts()
  {
    
    loadView()
  //  sut.displayPosts(viewModel: [PostFieldsViewModel])
    
  }
}
