//
//  PostDetailsRouter.swift
//  VIP-Demo
//
//  Created by admin on 4/1/19.
//  Copyright (c) 2019 admin. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol PostDetailsRoutingLogic
{
  func routeToSomewhere()
}

protocol PostDetailsDataPassing
{
  var dataStore: PostDetailsDataStore? { get }
}

class PostDetailsRouter: NSObject, PostDetailsRoutingLogic, PostDetailsDataPassing
{
  weak var viewController: PostDetailsViewController?
  var dataStore: PostDetailsDataStore?
  
  // MARK: Routing
  
  func routeToSomewhere()
  {
//      let storyboard = UIStoryboard(name: "Main", bundle: nil)
//      let destinationVC = storyboard.instantiateViewController(withIdentifier: "SomewhereViewController") as! SomewhereViewController
//      var destinationDS = destinationVC.router!.dataStore!
//      passDataToSomewhere(source: dataStore!, destination: &destinationDS)
//      navigateToSomewhere(source: viewController!, destination: destinationVC)
  }

  // MARK: Navigation
  
//  func navigateToSomewhere(source: PostDetailsViewController, destination: SomewhereViewController)
//  {
//    source.show(destination, sender: nil)
//  }
  
  // MARK: Passing data
  
//  func passDataToSomewhere(source: PostDetailsDataStore, destination: inout SomewhereDataStore)
//  {
//    destination.posts = source.posts
//  }
}
