//
//  PostDetailsWorker.swift
//  VIP-Demo
//
//  Created by admin on 4/1/19.
//  Copyright (c) 2019 admin. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com


import UIKit

class PostDetailsWorker
{
    func fetchPosts(completion: @escaping ([PostDetails.Post.Response]?, Error?) -> ())
  {
    guard let publicUrl = URL(string: APPURL.BaseURL + APPURL.UrlCollection.UserDetailUrl.UserPosts) else { return }
    URLSession.shared.dataTask(with: publicUrl) { (data, response
        , error) in
        guard let data = data else { return }
        do {
            let decoder = JSONDecoder()
            let publicData = try decoder.decode([PostDetails.Post.Response].self, from: data)
            
            completion(publicData,nil)
        } catch let err {
            print("Err", err)
            completion(nil,err)
        }
        }.resume()
  }
}
