//
//  PostDetailsInteractor.swift
//  VIP-Demo
//
//  Created by admin on 4/1/19.
//  Copyright (c) 2019 admin. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol PostDetailsBusinessLogic
{
    func fetchPosts(request: PostDetails.Post.Request)
}

protocol PostDetailsDataStore
{
    
}

class PostDetailsInteractor: PostDetailsBusinessLogic, PostDetailsDataStore
{
    var posts: [PostFieldsViewModel] = []
    var presenter: PostDetailsPresentationLogic?
    var worker: PostDetailsWorker?
    //var name: String = ""
    
    // MARK: Do something
    
    func fetchPosts(request: PostDetails.Post.Request)
    {
        worker = PostDetailsWorker()
        worker?.fetchPosts(completion: { (response , error) in
            if let responseData = response{
                self.presenter?.presentPosts(response: responseData)
            }else{
                print("error")
            }
        })
        
    }
}
