//
//  PostDetailsModels.swift
//  VIP-Demo
//
//  Created by admin on 4/1/19.
//  Copyright (c) 2019 admin. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum PostDetails
{
  // MARK: Use cases
  
  enum Post
  {
    struct Request
    {
        
    }
    
    struct Response:Codable
    {
        var userId:Int?
        var id:Int?
        var title:String?
        var body:String?
    }
  }
}
